-- EMPLOYEE
CREATE TABLE EMPLOYEE (
    SSN CHAR(9),             -- 사회보장번호
    FNAME VARCHAR(50),       -- First name
    MINIT VARCHAR(50),       -- Minit
    LNAME VARCHAR(50),       -- Last name
    BDATE DATE,              -- Birth Date
    ADDRESS VARCHAR(100),    -- Address
    SEX CHAR(1),             -- Sex
    SALARY DECIMAL(10, 2),   -- Salary
    SUPERSSN CHAR(9),        -- SSN of supervisor
    DNO INT,                 -- Number of Department
    PRIMARY KEY (SSN)        -- PRIMARY KEY 정의를 괄호로 감싸야 함
);

CREATE TABLE DEPARTMENT(
    DNAME VARCHAR(30),
    DNUMBER INT,
    MGRSSN CHAR(9),
    MGRSTARTDATE DATE,
    PRIMARY KEY (DNUMBER)
);

-- Multi-valued attribute : Handles multiple locations for a Department
CREATE TABLE DEPT_LOCATIONS(
    DNUMBER INT,
    DLOCATION VARCHAR(100),
    PRIMARY KEY(DNUMBER, DLOCATION)
);

CREATE TABLE PROJECT(
    PNAME VARCHAR(50),
    PNUMBER INT,
    PLOCATION VARCHAR(100),
    DNUM INT,
    PRIMARY KEY (PNUMBER)
);

CREATE TABLE WORKS_ON(
    ESSN CHAR(9),
    PNO INT,
    HOURS INT,
    PRIMARY KEY (ESSN, PNO)
);

CREATE TABLE DEPENDENT(
    ESSN CHAR(9),
    DEPENDENT_NAME VARCHAR(100),
    SEX CHAR(1),
    BDATE DATE,
    RELATIONSHIP VARCHAR(100),
    PRIMARY KEY (ESSN, DEPENDENT_NAME)
);

-- The SUPERSSN in the EMPLOYEE table references the SSN of the EMPLOYEE table
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_SUPERVISOR FOREIGN KEY (SUPERSSN) REFERENCES EMPLOYEE(SSN);

-- The DNO in the EMPLOYEE table references the DNUMBER of the DEPARTMENT table
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER);

-- The MGRSSN in the DEPARTMENT table references the SSN of the EMPLOYEE table
ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_MANAGER FOREIGN KEY (MGRSSN) REFERENCES EMPLOYEE(SSN);

-- The DNUMBER in the DEPT_LOCATIONS table references the DNUMBER of the DEPARTMENT table
ALTER TABLE DEPT_LOCATIONS
ADD CONSTRAINT FK_DEPT_LOCATIONS_DEPARTMENT FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER);

-- The DNUM in the PROJECT table references the DNUMBER of the DEPARTMENT table
ALTER TABLE PROJECT
ADD CONSTRAINT FK_PROJECT_DEPARTMENT FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUMBER);

-- The ESSN in the WORKS_ON table references the SSN of the EMPLOYEE table
ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_WORKS_ON_EMPLOYEE FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN);

-- The PNO in the WORKS_ON table references the PNUMBER of the PROJECT table
ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_WORKS_ON_PROJECT FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER);

-- The ESSN in the DEPENDENT table references the SSN of the EMPLOYEE table
ALTER TABLE DEPENDENT
ADD CONSTRAINT FK_DEPENDENT_EMPLOYEE FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN);

-- EMPLOYEE
-- INSERT INTO EMPLOYEE (SSN, FNAME, MINIT, LNAME, BDATE, ADDRESS, SEX, SALARY, SUPERSSN, DNO)
-- VALUES 
--     ('123456789', 'John', 'B', 'Smith', '1965-01-09', '731 Fondren, Houston, TX', 'M', 30000.00, NULL, NULL);

-- DROP TABLE IF EXISTS DEPENDENT;
-- DROP TABLE IF EXISTS WORKS_ON;
-- DROP TABLE IF EXISTS DEPT_LOCATIONS;
-- DROP TABLE IF EXISTS PROJECT;

-- -- 외래 키 삭제
-- ALTER TABLE EMPLOYEE
-- DROP FOREIGN KEY FK_EMPLOYEE_SUPERVISOR;

-- ALTER TABLE EMPLOYEE
-- DROP FOREIGN KEY FK_EMPLOYEE_DEPARTMENT;

-- ALTER TABLE DEPARTMENT
-- DROP FOREIGN KEY FK_DEPARTMENT_MANAGER;

-- -- 필요시 다른 외래 키도 제거

-- -- 테이블 삭제
-- DROP TABLE IF EXISTS DEPENDENT;
-- DROP TABLE IF EXISTS WORKS_ON;
-- DROP TABLE IF EXISTS DEPT_LOCATIONS;
-- DROP TABLE IF EXISTS PROJECT;
-- DROP TABLE IF EXISTS DEPARTMENT;
-- DROP TABLE IF EXISTS EMPLOYEE;